experiment_name: bimodal_gaussian_2
seeds:
  - 1
  - 2
  - 3
verbosity: 1
data:
  means:
    - [[2, 2], [-2, -2]]
  covs:
    - [[[1, 0], [0, 1]], [[1, 0], [0, 1]]]
    - [[[3, 0.7], [0.7, 4]], [[0.5, 0], [0, 3]]]
  weights:
    - [0.75, 0.25]
  num_samples: 500
mcmc_samples:
  - 500
burnin:
  - 0
n_batches:
  - 5
step_size:
  - 0.05
init_m:
  - identity
  - fisher_approx
mdecay:
  - 0.02
mresampling:
  - 0.0
