experiment_name: minimal example
seed: 567
verbosity: 2
plot:
  xlim: [-3, 5]
  ylim: [-1, 7]
data:
  means:
    - [[1,3]]
  covs:
    - [[[1, 0.9], [0.9, 1]]]
    - [[[1, 0], [0, 1]]]
  weights:
    - [1]
  num_samples: 1000
init_position: [0.0,0.0]
mcmc_samples:
  - 500
burnin:
  - 0
n_batches:
  - 5
step_size:
  - 0.05
init_m:
  - fisher
mdecay:
  - 0.05
mresampling:
  - 0.01
