experiment_name: minimal example
seeds:
  - 567
verbosity: 2
data:
  means:
    - [[0,0]]
  covs:
    - [[[1, 0], [0, 1]]]
  weights:
    - [1]
  num_samples: 1000
init_position: [0.0,0.0]
mcmc_samples:
  - 500
burnin:
  - 0
n_batches:
  - 5
step_size:
  - 0.1
  - 0.05
init_m:
  - fisher
mdecay:
  - 0.05
mresampling:
  - 0.01
