experiment_name: mixture_gaussian
seed: 567
verbosity: 1
data:
  means:
    - [[4, 4], [-4, 4], [-4, -4], [4, -4]]
  covs:
    - [[[1, 0], [0, 1]], [[1, 0], [0, 1]], [[1, 0], [0, 1]], [[1, 0], [0, 1]]]
  weights:
    - [0.25, 0.25, 0.25, 0.25]
  num_samples: 1000
mcmc_samples:
  - 2000
burnin:
  - 200
n_batches:
  - 5
step_size:
  - 0.01
  - 0.05
init_m:
  - identity
  - fisher
mdecay:
  - 0.01
  - 0.05
mresampling:
  - 0.0
  - 0.01
