# QUESTION: Do you think the hyperparameters are reasonably chosen especially for SGHMC? # ES: regarding mixture params - depends on what you want to show
# but does not look odd. for sghmc looks good, step size is highly task specific mdecay and mom-resamp good. n batches/ batch size has also an effect but seems reasonable here :)
experiment_name: mixture_gaussian
seed: 567
verbosity: 1
data:
  means:
    - [[4, 4], [-4, 4], [-4, -4], [4, -4]]
  covs:
    - [[[1, 0], [0, 1]], [[1, 0], [0, 1]], [[1, 0], [0, 1]], [[1, 0], [0, 1]]]
    - [[[1, 0.9], [0.9, 1]], [[0.4, 0], [0, 1]], [[0.8, 0.4], [0, 1]], [[5, 0], [0, 3]]]
  weights:
    - [0.25, 0.25, 0.25, 0.25]
  num_samples: 1000
mcmc_samples:
  - 4000
burnin:
  - 0
n_batches:
  - 5
step_size:
  - 0.01
  - 0.05
init_m:
  - identity
  - fisher
mdecay:
  - 0.01
  - 0.05
mresampling:
  - 0.0
