#TODO: do a more easy example with only two modes
experiment_name: mixture_gaussian
seeds:
  - 1
  - 2
  - 3
verbosity: 1
data:
  means:
    - [[4, 4], [-4, 4], [-4, -4], [4, -4]]
  covs:
    - [[[3, 0.7], [0.7, 4]], [[0.5, 0], [0, 3]], [[2, 0.4], [0, 3]], [[6, 0], [0, 6]]]
    - [[[1, 0], [0, 1]], [[1, 0], [0, 1]], [[1, 0], [0, 1]], [[1, 0], [0, 1]]]
  weights:
    - [0.25, 0.25, 0.25, 0.25]
  num_samples: 2000
mcmc_samples:
  - 2000
burnin:
  - 0
n_batches:
  - 5
step_size:
  - 0.01
  - 0.05
init_m:
  - identity
  - fisher
mdecay:
  - 0.01
  - 0.05
mresampling:
  - 0.0
