experiment_name: unimodal_gaussian
seeds:
  - 1
  - 2
  - 3
verbosity: 2
data:
  means:
    - [[0,0]]
  covs:
    - [[[1, 0], [0, 1]]]
    - [[[5, 0], [0, 0.2]]]
  weights:
    - [1]
  num_samples: 1000
mcmc_samples:
  - 4000
burnin:
  - 0
n_batches:
  - 5
step_size:
  - 0.01
  - 0.05
init_m:
  - identity
  - fisher
mdecay:
  - 0.01
  - 0.05
mresampling:
  - 0.0
