# QUESTION: Do you think the hyperparameters are reasonably chosen especially for SGHMC?
experiment_name: unimodal_gaussian
seed: 567
verbosity: 1
plot:
  xlim: [-3, 5]
  ylim: [-1, 7]
data:
  means:
    - [[1,3]]
  covs:
    - [[[1, 0], [0, 1]]]
    - [[[0.4, 0.6], [0.6, 1]]]
  weights:
    - [1]
  num_samples: 1000
mcmc_samples:
  - 4000
burnin:
  - 0
n_batches:
  - 5
step_size:
  - 0.01
  - 0.05
init_m:
  - identity
  - fisher
mdecay:
  - 0.01
  - 0.05
mresampling:
  - 0.0
