experiment_name: unimodal_gaussian
seed: 567
data:
  means:
    - [1,3]
  covs:
    - [[[1, 0], [0, 1]]]
    - [[[1, 0.9], [0.9, 1]]]
  weights:
    - 1
  num_samples: 1000
mcmc_samples:
  - 2000
burnin:
  - 200
n_batches:
  - 5
step_size:
  - 0.01
  - 0.05
init_m:
  - identity
  - fisher
mdecay:
  - 0.01
  - 0.05
mresampling:
  - 0
  - 0.01
